### Multiple Linear Regression

In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.datasets import make_regression
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
# data

X, y = make_regression(n_samples=100, n_features=3, noise=0.1, random_state=42)

In [3]:
# splitting

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) 

In [4]:
# model

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [5]:
# make prediction

y_pred = model.predict(X_test)

In [6]:
# evaluating

mse = mean_squared_error(y_test, y_pred)

r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")

Mean Squared Error: 0.012384680824794976
R-squared: 0.9999982803305351


In [7]:
# coeff and intercept

print("Coefficients:", model.coef_)
print("Intercept:", model.intercept_)

Coefficients: [28.2063702  75.05481391 17.75432807]
Intercept: 0.013037594527229857


#### from scratch

In [8]:
# data

X = [[2,3],
     [3,5],
     [6,3],
     [7,2]]
X = np.array(X)

# y = 2*x1 + 3*x2 + 1

y = np.array([14,22,22,21])

In [9]:
X.shape

(4, 2)

In [10]:
y.shape

(4,)

In [11]:
# initialising some variables

no_data_points, no_features = X.shape
learning_rate = 0.05
num_iterations = 10000
weights = np.zeros(no_features)
bias = 0

In [12]:
weights

array([0., 0.])

In [13]:
# sample y calculation

sample = np.dot(X, weights) + bias
sample

array([0., 0., 0., 0.])

In [14]:
sample.shape

(4,)

In [16]:
# gradient descent

for i in range(num_iterations):
  linear_model = np.dot(X, weights) + bias # shape = (n,) , it is 1d

  error = linear_model - y # determining the error
  error_applied_to_features = np.dot(X.T, error) # applying error to each samples

  gradient_weights = (1/ no_data_points) * error_applied_to_features
  gradient_bias = (1/ no_data_points) * np.sum(error)

  weights -= learning_rate * gradient_weights
  bias -= learning_rate * gradient_bias

  if i % 1000 == 0:
    print(weights, bias)

[2.00000003 3.00000007] 0.9999996290717769
[2.00000001 3.00000002] 0.9999999040998545
[2. 3.] 0.9999999752058835
[2. 3.] 0.9999999935897049
[2. 3.] 0.9999999983426757
[2. 3.] 0.9999999995715125
[2. 3.] 0.9999999998892186
[2. 3.] 0.9999999999713589
[2. 3.] 0.9999999999925957
[2. 3.] 0.9999999999980845


In [17]:
weights

array([2., 3.])

In [18]:
bias

0.9999999999995026